### PR TITLE
Version checking should not in onEnable.

### PR DESCRIPTION
**Pull request by SNWCreations**

### CODE REVIEW

**Comment by SNWCreations** [comment]
And can you provide a compiled version of new version if possible? :D

**Comment by katorly** [comment]
The fact is that the file that `pluginupdater()` depended on has been deleted.  
But I'll solve this anyway

**Comment by SNWCreations** [comment]
And I have a suggestion.  You can turn this project into a Maven project.

**Comment by katorly** [comment]
> And I have a suggestion. You can turn this project into a Maven project.

It's actually Maven, though

**Pull request merged**
